name: rainery
description: Weather app.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  geolocator: ^9.0.1
  google_fonts: ^3.0.1
  http: ^0.13.5
  iconsax: ^0.0.8
  intl: ^0.17.0
  loading_animation_widget: ^1.2.0+2
  provider: ^6.0.3
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  # fonts:
  #   - family: NotoSans
  #     fonts:
  #       - asset: assets/fonts/NotoSansJP-Regular.otf
  #       - asset: assets/fonts/NotoSansJP-Bold.otf
